version: "2"
run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly

linters:
  default: all
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment # Too strict for readability

    gocyclo:
      min-complexity: 15

    cyclop:
      max-complexity: 15

    dupl:
      threshold: 100

    goconst:
      min-len: 2
      min-occurrences: 3

    misspell:
      locale: US

    lll:
      line-length: 140

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - unnamedResult # Can be useful in some cases

    funlen:
      lines: 100
      statements: 50

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G404 # Insecure random number source - we're not using crypto random for UUIDs
        - G107 # Url provided to HTTP request as taint input - false positives in tests

    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"
        - name: var-naming
          arguments:
            - [
                "ID",
                "API",
                "HTTP",
                "JSON",
                "URL",
                "UUID",
                "SQL",
                "DB",
                "TLS",
                "TCP",
                "UDP",
                "IP",
                "CORS",
                "CSRF",
                "XSS",
              ]

    nestif:
      min-complexity: 4

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    nakedret:
      max-func-lines: 30

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: ""

output:
  # Use multiple output formats for different purposes
  formats:
    # Default colored text output for human readability
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true

    # JSON output for CI/CD integration and tooling
    json:
      path: ./golangci-lint-report.json

    # SARIF format for security tools and GitHub integration
    sarif:
      path: ./golangci-lint-report.sarif

  # Configure path handling
  path-mode: "" # Use relative paths for better portability
  path-prefix: ""

  # Sort results for consistent output
  sort-order:
    - linter
    - severity
    - file

  # Show statistics for CI reporting
  show-stats: true
