run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly

# Configuration version
version: "2"

linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/coolguy1771/wastebin
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
  funlen:
    lines: 100
    statements: 50
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G404  # Insecure random number source - we're not using crypto random for UUIDs
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
  cyclop:
    max-complexity: 15
  nestif:
    min-complexity: 4
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

linters:
  enable:
    # Core linters (always recommended)
    - errcheck      # Check for unhandled errors
    - govet         # Standard Go vet checks
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Detect unused constants, variables, functions and types
    
    # Style and formatting
    - revive        # Replacement for golint
    - whitespace    # Detect unnecessary whitespace
    
    # Code quality
    - bodyclose     # Check if HTTP response body is closed
    - dupl          # Code duplication
    - goconst       # Repeated strings that could be constants
    - gocritic      # Go source code linter providing checks currently missing from other linters
    - gocyclo       # Cyclomatic complexity
    - gosec         # Security checks
    - misspell      # Spelling mistakes
    - unconvert     # Unnecessary type conversions
    - unparam       # Unused function parameters
    
    # Performance
    - prealloc      # Find slice declarations that could potentially be pre-allocated
    
    # Additional checks
    - funlen        # Function length
    - lll           # Line length
    - nakedret      # Naked returns
    - nestif        # Nested if statements
    - cyclop        # Cyclomatic complexity

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: ""