project_name: "wastebin"

archives:
  - id: "main"
    wrap_in_directory: true
    format: "tar.gz"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "README.md"
      - "LICENSE"
      - "CHANGELOG.md"

builds:
  - id: "wastebin"
    main: "./cmd/wastebin"
    binary: "wastebin"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goos:
      - "darwin"
      - "linux"
      - "freebsd"
      - "openbsd"
    ignore:
      - goos: "freebsd"
        goarch: "arm"
      - goos: "openbsd"
        goarch: "arm"
      - goos: "freebsd"
        goarch: "arm64"
      - goos: "openbsd"
        goarch: "arm64"
    env:
      - "CGO_ENABLED=1"
    flags:
      - "-trimpath"
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }}"
    mod_timestamp: "{{ .CommitTimestamp }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

signs:
  - artifacts: checksum
  - cmd: cosign
    args:
      - "sign-blob"
      - "--key"
      - "./cosign.key"
      - "--output"
      - "{{ .ArtifactPath }}.sig"
      - "{{ .ArtifactPath }}"

