project_name: "wastebin"
archives:
  - id: main
    wrap_in_directory: true
    files:
      - "README.md"
builds:
  - main: "./cmd/wastebin"
    binary: "wastebin"
    goarch:
      - "386"
      - "amd64"
    goos:
      - "darwin"
      - "linux"
      - "freebsd"
      - "openbsd"
    env:
      - CGO_ENABLED=1
