global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
    scrape_interval: 30s

  # Wastebin application (if it exposes Prometheus metrics directly)
  - job_name: 'wastebin'
    static_configs:
      - targets: ['wastebin:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s