name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  packages: write
  attestations: write
  id-token: write
  checks: write
  pull-requests: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  security:
    name: Security
    uses: ./.github/workflows/security.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    needs: [lint, test]
    uses: ./.github/workflows/build.yml

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [lint, security, test, build]
    if: always()
    steps:
      - name: Check Results
        run: |
          echo "## CI Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Lint | ${{ needs.lint.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Security | ${{ needs.security.result == 'success' && '✅ Passed' || needs.security.result == 'skipped' && '⏭️ Skipped' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Test | ${{ needs.test.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ needs.build.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY

      - name: Check for failures
        if: needs.lint.result == 'failure' || needs.security.result == 'failure' || needs.test.result == 'failure' || needs.build.result == 'failure'
        run: |
          echo "❌ One or more CI checks failed!"
          exit 1

      - name: Success notification
        if: needs.lint.result == 'success' && (needs.security.result == 'success' || needs.security.result == 'skipped') && needs.test.result == 'success' && needs.build.result == 'success'
        run: echo "✅ All CI checks passed!"